POST http://localhost:3002/api/user
Content-Type: application/json

{
    "name": "entrenador4",
    "password": "entrenador4"
}

###

POST http://localhost:3002/api/user
Content-Type: application/json

{
}
